# Generated by Django 3.1.1 on 2020-09-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('image', models.ImageField(null=True, upload_to='%Y/%m/%d')),
                ('level', models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('user', 'user')], max_length=8, verbose_name='level')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': 'smart_mirror_user',
                'verbose_name_plural': 'smart_mirror_users',
                'db_table': 'smart_mirror_user',
            },
        ),
    ]
